# This file was generated by GoReleaser. DO NOT EDIT.
cask "forgeui" do
  name "forgeui"
  desc "SSR-first UI framework for Go with 35+ components, Tailwind CSS, and Alpine.js integration"
  homepage "https://github.com/xraph/forgeui"
  version "1.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "forgeui"

  on_macos do
    on_intel do
      url "https://github.com/xraph/forgeui/releases/download/v#{version}/forgeui-#{version}-darwin-x86_64.tar.gz"
      sha256 "7c8313c409c86e5f1a96fa27ee1f150bb66339e2587d7d740a200dade5554f46"
    end
    on_arm do
      url "https://github.com/xraph/forgeui/releases/download/v#{version}/forgeui-#{version}-darwin-arm64.tar.gz"
      sha256 "51bdf932cefc00d86722ddd14a3cf64b8d450b58b01dddd3d490d8974acac50f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/xraph/forgeui/releases/download/v#{version}/forgeui-#{version}-linux-x86_64.tar.gz"
      sha256 "a6eaa26c43b83625a6d5dc7195218675b48901d7647847c3b3af4f9ad415c29f"
    end
    on_arm do
      url "https://github.com/xraph/forgeui/releases/download/v#{version}/forgeui-#{version}-linux-arm64.tar.gz"
      sha256 "4c60de9e0f2686baf45d529791d2763bd7df231a2cf6a8e42c16b6fb28be9a69"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/forgeui"]
    end
  end

  caveats do
    "Run 'forgeui --help' to get started"
  end

  # No zap stanza required
end
