# This file was generated by GoReleaser. DO NOT EDIT.
cask "forgeui" do
  name "forgeui"
  desc "SSR-first UI framework for Go with 35+ components, Tailwind CSS, and Alpine.js integration"
  homepage "https://github.com/xraph/forgeui"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "forgeui"

  on_macos do
    on_intel do
      url "https://github.com/xraph/forgeui/releases/download/v#{version}/forgeui-#{version}-darwin-x86_64.tar.gz"
      sha256 "38c11c94f5a5c8dd354f34c994b590b70b1b9308647ccc61519bcec798e33de8"
    end
    on_arm do
      url "https://github.com/xraph/forgeui/releases/download/v#{version}/forgeui-#{version}-darwin-arm64.tar.gz"
      sha256 "309936ab3c92f99b6c7f47dfb42e92938585c225b42288a222ba66d9a925ee9d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/xraph/forgeui/releases/download/v#{version}/forgeui-#{version}-linux-x86_64.tar.gz"
      sha256 "b14955ab6903634eb8413e7ce018dceb9adddb95de18933226a6c1c49c6dc165"
    end
    on_arm do
      url "https://github.com/xraph/forgeui/releases/download/v#{version}/forgeui-#{version}-linux-arm64.tar.gz"
      sha256 "101ca9164130ee31415199e25cf98ff2d8a3ad637af98ef1b6e6d39cb09effc7"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/forgeui"]
    end
  end

  caveats do
    "Run 'forgeui --help' to get started"
  end

  # No zap stanza required
end
