# This file was generated by GoReleaser. DO NOT EDIT.
cask "forgeui" do
  name "forgeui"
  desc "SSR-first UI framework for Go with 35+ components, Tailwind CSS, and Alpine.js integration"
  homepage "https://github.com/xraph/forgeui"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "forgeui"

  on_macos do
    on_intel do
      url "https://github.com/xraph/forgeui/releases/download/v#{version}/forgeui-#{version}-darwin-x86_64.tar.gz",
        verified: "github.com/xraph/forgeui"
      sha256 "a8e15f97f551318796320bdd2266fba159a7a6f7f32be33d72145be730926084"
    end
    on_arm do
      url "https://github.com/xraph/forgeui/releases/download/v#{version}/forgeui-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/xraph/forgeui"
      sha256 "ceaef3b7ee3bbd0aecb94bd20030bfc5e50d9ec7f6374d2595935c661928e7ce"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/xraph/forgeui/releases/download/v#{version}/forgeui-#{version}-linux-x86_64.tar.gz",
        verified: "github.com/xraph/forgeui"
      sha256 "6da985412200148337f28e6b6ab79b71ffa038d3003816d95a44e94fa522024b"
    end
    on_arm do
      url "https://github.com/xraph/forgeui/releases/download/v#{version}/forgeui-#{version}-linux-arm64.tar.gz",
        verified: "github.com/xraph/forgeui"
      sha256 "befbb99d65aef930c25e6e45252a5a16802cbed7472a3a2796f151e601dc426b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/forgeui"]
    end
  end

  # No zap stanza required
end
