# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forge < Formula
  desc "Comprehensive backend framework for Go with enterprise-grade features"
  homepage "https://github.com/xraph/forge"
  version "0.1.11"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xraph/forge/releases/download/v0.1.11/forge-0.1.11-darwin-x86_64.tar.gz"
      sha256 "d1c1ffa45ca2b8a26716dd54be5d08f470e5542a058505a92102a8048c22f86c"

      def install
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xraph/forge/releases/download/v0.1.11/forge-0.1.11-darwin-arm64.tar.gz"
      sha256 "48064a32fe539bfec945380647e09128ecec35e6de1c80f31106716279ab30eb"

      def install
        bin.install "forge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xraph/forge/releases/download/v0.1.11/forge-0.1.11-linux-x86_64.tar.gz"
      sha256 "bea244db67274311f4d92e1ed8c2639245c79c45eed73c6e5dd67edce0d6325a"
      def install
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xraph/forge/releases/download/v0.1.11/forge-0.1.11-linux-arm64.tar.gz"
      sha256 "7bfe5037881fe06d0955b9aba07a42c10204fbbc5b4a8c46fbd6ccc9859dbbc6"
      def install
        bin.install "forge"
      end
    end
  end

  test do
    system "#{bin}/forge", "version"
  end
end
