# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forgeui < Formula
  desc "SSR-first UI framework for Go with 35+ components, Tailwind CSS, and Alpine.js integration"
  homepage "https://github.com/xraph/forgeui"
  version "0.0.7"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xraph/forgeui/releases/download/v0.0.7/forgeui-0.0.7-darwin-x86_64.tar.gz"
      sha256 "d4458a4fa6d8841bd2a2b66827264e872fda279ffd633bc02a78c069b6e32e05"

      def install
        bin.install "forgeui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xraph/forgeui/releases/download/v0.0.7/forgeui-0.0.7-darwin-arm64.tar.gz"
      sha256 "c5e7b9ae7adc613281f114a3b5e501e3ad3d7aca33dd164a4f7ba9f533a350c6"

      def install
        bin.install "forgeui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xraph/forgeui/releases/download/v0.0.7/forgeui-0.0.7-linux-x86_64.tar.gz"
      sha256 "800dc41ae20afde09219fa4d8da1b2eeb84b4358d2555e26e51eea64d4d05665"
      def install
        bin.install "forgeui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xraph/forgeui/releases/download/v0.0.7/forgeui-0.0.7-linux-arm64.tar.gz"
      sha256 "8e157cd4c88c97da42631617a5509ebc3ec22ad1a1312cb41db17373b64766d6"
      def install
        bin.install "forgeui"
      end
    end
  end

  test do
    system "#{bin}/forgeui", "--version"
  end
end
