# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forge < Formula
  desc "Comprehensive backend framework for Go with enterprise-grade features"
  homepage "https://github.com/xraph/forge"
  version "0.9.12"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xraph/forge/releases/download/v0.9.12/forge-0.9.12-darwin-x86_64.tar.gz"
      sha256 "3b3ec9fd2ba911d0de4f1558bf563938f79bc05b8475709362ca4ac6501d08d5"

      def install
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xraph/forge/releases/download/v0.9.12/forge-0.9.12-darwin-arm64.tar.gz"
      sha256 "8f0ba425fdc23a08c960c5b2854cc3f93de7938310ceca4b24861b808cca5291"

      def install
        bin.install "forge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xraph/forge/releases/download/v0.9.12/forge-0.9.12-linux-x86_64.tar.gz"
      sha256 "7afc0155a5480ddb4d5bf3220f0f0bf233036017d29dfe47a3083ebad4f0ede7"
      def install
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xraph/forge/releases/download/v0.9.12/forge-0.9.12-linux-arm64.tar.gz"
      sha256 "24b940f6a6d9a6d0d6c9ab1378394b01c6b2e78fe4a06afea05c9f8590dd70f7"
      def install
        bin.install "forge"
      end
    end
  end

  test do
    system "#{bin}/forge", "version"
  end
end
