# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forgeui < Formula
  desc "SSR-first UI framework for Go with 35+ components, Tailwind CSS, and Alpine.js integration"
  homepage "https://github.com/xraph/forgeui"
  version "0.0.8"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xraph/forgeui/releases/download/v0.0.8/forgeui-0.0.8-darwin-x86_64.tar.gz"
      sha256 "e924578f6ab65706692e8a3c53ab7df218cbe549cb1afb67efa1d30292bfa761"

      def install
        bin.install "forgeui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xraph/forgeui/releases/download/v0.0.8/forgeui-0.0.8-darwin-arm64.tar.gz"
      sha256 "903871798d44e95438a0e7fea1b3db703ee27d6dedfbe49c28fc0f3d51557c63"

      def install
        bin.install "forgeui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xraph/forgeui/releases/download/v0.0.8/forgeui-0.0.8-linux-x86_64.tar.gz"
      sha256 "e6de58133d42027f19816ab20d2645eb0482b7fe251c76bc0ef47343e93222d5"
      def install
        bin.install "forgeui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xraph/forgeui/releases/download/v0.0.8/forgeui-0.0.8-linux-arm64.tar.gz"
      sha256 "a99b5db0657e844ec2066edd856b1ff023ff4ce3e89f83263512155401b771c0"
      def install
        bin.install "forgeui"
      end
    end
  end

  test do
    system "#{bin}/forgeui", "--version"
  end
end
