# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forgeui < Formula
  desc "SSR-first UI framework for Go with 35+ components, Tailwind CSS, and Alpine.js integration"
  homepage "https://github.com/xraph/forgeui"
  version "0.0.6"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xraph/forgeui/releases/download/v0.0.6/forgeui-0.0.6-darwin-x86_64.tar.gz"
      sha256 "7bcb69985a30df9721fad8a49d0523df0b5b950c6dd74f78ee39412062e534f4"

      def install
        bin.install "forgeui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xraph/forgeui/releases/download/v0.0.6/forgeui-0.0.6-darwin-arm64.tar.gz"
      sha256 "db1fa8b7d366ce75083638f8e88c82e4ece33b3ffa8454533ba68b184d16843e"

      def install
        bin.install "forgeui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xraph/forgeui/releases/download/v0.0.6/forgeui-0.0.6-linux-x86_64.tar.gz"
      sha256 "fc3851f541ad9b89d84aa889e7eea858c002c1384872cdc5e605ac689ac835b1"
      def install
        bin.install "forgeui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xraph/forgeui/releases/download/v0.0.6/forgeui-0.0.6-linux-arm64.tar.gz"
      sha256 "f4f78ecffc34e70fbd7a2b46c3462afe94b2dffda8744acf3cc9daf1a25558d6"
      def install
        bin.install "forgeui"
      end
    end
  end

  test do
    system "#{bin}/forgeui", "--version"
  end
end
